### ISSUE TITLE
Isn't working well in android chrome

### ISSUE THREAD

**Issue by supresencia** [benkaiser/stretto#105]
Hello,

First of all, amazing job, congratulations!

Currently we are using your app as kiosks in android tablets, something like a music kiosk, we created a custom theme but for any strange reason the app isn't working well, here are the details.
1. We are usinng HP slate 21 pro running Android Kitkat, last version of chrome, we already made the test with different browsers and android versions... Firefox, Chrome beta, Chrome Dev, default android browser...
2. The browser doesn't load the app (I mean doesn't run the js functions) (most of the times) we need to reload many times in order to make it work.
3. In order to make it work it was necessary to force the desktop version.

Some questions:
1. Could it be an Android version problem?
2. Is it possible to build an Android app using the current stretto code?
3. Have you ever heard about any similar problem?
4. Do you have any guide in order to create custom themes?

**Comment by benkaiser** [comment]
Cheers for the kind words.

That sounds like an interesting use. Is it in a retail setup? or more personal use?

Regarding the mobile version being broken, I looked at the mobile version on master and it appears to be playing songs, changing playlists, etc just fine. Is their more information you can give than "doesn't run the js functions", which js functions / what isn't happening?
As for forcing the desktop version. If it's a permanent thing you can just remove the mobile detection from `routes/index.js:107`.

Answering your specific questions:
1. Possibly but I doubt it, I own a nexus 6p running Marshmellow, so that is the version of android I'm not experiencing it on. Also I use chrome beta, but they shouldn't really differ too much at all.
2. Well you can build it with the same idea in mind, but it would have to be a complete rewrite to Java. I have thought about creating an android app and did some research / initial work with nativescript a few months back (a technology that compiles javascript to native Java/Objective-C. But the platform was still in it's infancy and wasn't ready for me to build an app just yet. Also there is a lot of work in it and I for the foreseeable future will be quite busy with my university studies and then working.
3. Nope, not really. Most issues I get from people are either feature suggestions or issues with the desktop version.
4. It's mostly as simple as changing the bootstrap theme Stretto is using. But there are a few other things that have colors (the songs when you click them, etc) that you will want to change to match your color palette.

**Comment by ohnx** [comment]
@supresencia I've done a bit with theming Stretto, if you want any tips in terms of where to start, feel free to ask :)

@benkaiser The mobile version seems to be rather "trippy" for me, at least on an iPad mini:
![img_0205](https://cloud.githubusercontent.com/assets/6683648/15061103/481659c6-12ff-11e6-8894-0b893c8b24a2.PNG)

**Comment by benkaiser** [comment]
@ohnx well, it's geared towards a portrait phone screen (at least that's been my use case). So landscape on a tablet is bound to look weird! :)

**Comment by ohnx** [comment]
The bottom scrub bar doesn't seem to work, though - you can drag it to a point in the song, but it doesn't update.

**Comment by benkaiser** [comment]
Ahh I see. Perhaps it's an issue with the bootstrap slider library.

**Comment by ohnx** [comment]
There some more issues - modals don't seem to work.

I'll try out the web inspector feature and see what errors are being thrown.

**Comment by ohnx** [comment]
Funny! I try with web inspector the scrollbar works now!

The song information shows at the top, though:
![image](https://cloud.githubusercontent.com/assets/6683648/15061284/7dac785c-1301-11e6-81b6-339ada4a5bd9.PNG)

Also, modals still don't work - this error is thrown in the console:
![a](https://cloud.githubusercontent.com/assets/6683648/15061302/b7c078ea-1301-11e6-9adb-6e668f1e5a49.png)

**Comment by benkaiser** [comment]
Cheers for investigating.

The song info is supposed to be up the top, it's just how I did the design
for mobile.

But yeah the modals is an issue.

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
