### ISSUE TITLE
Transcoding/Conversion - Proof of Concept

### ISSUE THREAD

**Issue by nikkiii** [benkaiser/stretto#112]
I have a fork that has the transcoding mentioned in #14, with the help of #73, in a cleaner and more sensible way at https://github.com/nikkiii/stretto

It'll avoid converting unless the browser needs it (by providing multiple sources, both the original and mp3 versions), and stream it while converting. It needs some serious testing, and I've reformatted the source and done a few other modifications to it along the way.

I considered simply making a pull request, but since I've changed quite a bit and reformatted a few files, I figured if there was real interest I could merge it back/reformat it to match the project and create a PR, but until then it's a good proof of concept on the idea.

This fork might also feature Google Cast support soon... depending on if I feel like writing it or not

**Comment by benkaiser** [comment]
Hey @nikkiii 

That sounds like a great implementation, so if I'm understanding correctly it tries to use the default encoding of the file-type but if that fails it transcodes it into mp3? That sounds great because it seems now mp3 is supported everywhere, but this nicely allows you to keep it in the true file format.

If you'd like to reformat it so I'm just looking at the functionality changes, I'd love to take a look at a PR to see if we can have this merged :+1: 

For the Google Cast idea, would that mean a different view to that which is on the desktop? because currently you can just cast the page and that works fine :)

**Comment by nikkiii** [comment]
Yup - it adds the original file first, then adds an mp3 version if it's not mp3 by default, then I believe it uses them in order/attempts to use the first supported type. I'll look into the actual implementation. There are a few issues such as tracks sometimes not starting correctly (they start fine after conversion) - this should be a simple fix though?

As for Cast support, it'd be simply sending the music directly instead of using casting tabs, just an idea that might work better, but I'm not sure if it'll be done.

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
