### ISSUE TITLE
Scrollbar weird?

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#97]
Not sure about this, but the scrollbar in the main content area seems to be larger when at the top and smaller when at the bottom?...

**Comment by benkaiser** [comment]
Yeah could be likely. I have some hacks that do dynamic scrolling so that
not all the table rows are drawn, but only the ones visible (plus some
above and below). but due to my less than optimal implementation some bugs
like this can occur.

Anyway could you send a screenshot of the playlist this is occurring on? is
it really large or really small?

**Comment by ohnx** [comment]
It's a playlist of around 100 songs.

The wonky scrollbar also means that you can't really click and drag the scrollbar to control the position.

**Comment by benkaiser** [comment]
I'm pretty sure I've worked on this since then, is this still an issue?

**Comment by ohnx** [comment]
Since my pi died, I don't have a version of Stretto running anymore...

By the way, your demo `music.kaiserapps.com` seems to have stopped working.

**Comment by benkaiser** [comment]
Ah yes it does... I'll try fix that today

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
